-- migrate:up
REVOKE CREATE ON SCHEMA public FROM public;
CREATE USER goldfig WITH ENCRYPTED PASSWORD 'goldfig';
CREATE USER goldfig_ro WITH ENCRYPTED PASSWORD 'goldfig_ro';
GRANT ALL PRIVILEGES ON SCHEMA public TO goldfig;
GRANT ALL PRIVILEGES ON TABLE schema_migrations TO goldfig;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO goldfig_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE goldfig IN SCHEMA public GRANT SELECT ON TABLES TO goldfig_ro;
CREATE EXTENSION plv8;

-- migrate:down
DROP EXTENSION plv8;
ALTER DEFAULT PRIVILEGES FOR ROLE goldfig IN SCHEMA public REVOKE SELECT ON TABLES FROM goldfig_ro;
REVOKE SELECT ON ALL TABLES IN SCHEMA public FROM goldfig_ro;
REVOKE ALL PRIVILEGES ON TABLE schema_migrations FROM goldfig;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM goldfig;
DROP USER goldfig_ro;
DROP USER goldfig;
GRANT CREATE ON SCHEMA public TO public;